import { Gender } from './types';

const genderSpecificItems: Record<Gender, Record<string, string[]>> = {
  male: {
    'Heavy winter coat': ['Heavy winter coat', 'Parka', 'Down jacket'],
    'Winter coat': ['Winter coat', 'Wool coat', 'Peacoat'],
    'Light jacket': ['Light jacket', 'Bomber jacket', 'Denim jacket'],
    'Sweater': ['Sweater', 'Cardigan', 'Pullover'],
    'Long sleeve shirt': ['Long sleeve shirt', 'Button-down shirt', 'Polo shirt'],
    'Light sweater': ['Light sweater', 'Crew neck', 'V-neck'],
    'T-shirt': ['T-shirt', 'Crew neck', 'V-neck'],
    'Short sleeve shirt': ['Short sleeve shirt', 'Polo shirt', 'Casual shirt'],
    'Light pants': ['Chinos', 'Khakis', 'Lightweight pants'],
    'Thick pants': ['Thick pants', 'Jeans', 'Heavy-duty pants'],
    'Winter pants': ['Winter pants', 'Insulated pants', 'Fleece-lined pants'],
    'Tank top': ['Tank top', 'Sleeveless shirt', 'Muscle tee'],
    'Shorts': ['Shorts', 'Athletic shorts', 'Casual shorts'],
    'Rain jacket': ['Rain jacket', 'Waterproof jacket', 'Windbreaker'],
    'Umbrella': ['Compact umbrella', 'Windproof umbrella', 'Large umbrella'],
    'Waterproof shoes': ['Waterproof boots', 'Rain shoes', 'Waterproof sneakers'],
    'Waterproof boots': ['Waterproof boots', 'Snow boots', 'Winter boots'],
    'Snow jacket': ['Snow jacket', 'Insulated jacket', 'Winter coat'],
    'Waterproof gloves': ['Waterproof gloves', 'Winter gloves', 'Insulated gloves'],
    'Windbreaker': ['Windbreaker', 'Wind jacket', 'Lightweight jacket'],
    'Secure hat': ['Beanie', 'Winter hat', 'Baseball cap'],
    'Moisture-wicking fabrics': ['Moisture-wicking shirt', 'Athletic wear', 'Performance fabric'],
    'Extra deodorant': ['Deodorant', 'Antiperspirant', 'Body spray'],
    'Sunglasses': ['Sunglasses', 'Polarized sunglasses', 'UV protection glasses'],
    'Hat': ['Baseball cap', 'Sun hat', 'Bucket hat'],
    'Sunscreen': ['SPF 30+ sunscreen', 'Broad spectrum sunscreen', 'Water-resistant sunscreen'],
    'Light-colored clothing': ['Light colored shirt', 'Light pants', 'Light sweater']
  },
  female: {
    'Heavy winter coat': ['Heavy winter coat', 'Parka', 'Down jacket'],
    'Winter coat': ['Winter coat', 'Wool coat', 'Peacoat'],
    'Light jacket': ['Light jacket', 'Bomber jacket', 'Denim jacket'],
    'Sweater': ['Sweater', 'Cardigan', 'Pullover'],
    'Long sleeve shirt': ['Long sleeve shirt', 'Blouse', 'Tunic'],
    'Light sweater': ['Light sweater', 'Crew neck', 'V-neck'],
    'T-shirt': ['T-shirt', 'Crew neck', 'V-neck'],
    'Short sleeve shirt': ['Short sleeve shirt', 'Blouse', 'Casual top'],
    'Light pants': ['Chinos', 'Khakis', 'Lightweight pants'],
    'Thick pants': ['Thick pants', 'Jeans', 'Heavy-duty pants'],
    'Winter pants': ['Winter pants', 'Insulated pants', 'Fleece-lined pants'],
    'Tank top': ['Tank top', 'Camisole', 'Sleeveless top'],
    'Shorts': ['Shorts', 'Athletic shorts', 'Casual shorts'],
    'Dress': ['Dress', 'Sundress', 'Summer dress'],
    'Rain jacket': ['Rain jacket', 'Waterproof jacket', 'Windbreaker'],
    'Umbrella': ['Compact umbrella', 'Windproof umbrella', 'Large umbrella'],
    'Waterproof shoes': ['Waterproof boots', 'Rain shoes', 'Waterproof sneakers'],
    'Waterproof boots': ['Waterproof boots', 'Snow boots', 'Winter boots'],
    'Snow jacket': ['Snow jacket', 'Insulated jacket', 'Winter coat'],
    'Waterproof gloves': ['Waterproof gloves', 'Winter gloves', 'Insulated gloves'],
    'Windbreaker': ['Windbreaker', 'Wind jacket', 'Lightweight jacket'],
    'Secure hat': ['Beanie', 'Winter hat', 'Baseball cap'],
    'Moisture-wicking fabrics': ['Moisture-wicking shirt', 'Athletic wear', 'Performance fabric'],
    'Extra deodorant': ['Deodorant', 'Antiperspirant', 'Body spray'],
    'Sunglasses': ['Sunglasses', 'Polarized sunglasses', 'UV protection glasses'],
    'Hat': ['Baseball cap', 'Sun hat', 'Bucket hat'],
    'Sunscreen': ['SPF 30+ sunscreen', 'Broad spectrum sunscreen', 'Water-resistant sunscreen'],
    'Light-colored clothing': ['Light colored shirt', 'Light pants', 'Light sweater']
  },
  unisex: {
    'Heavy winter coat': ['Heavy winter coat', 'Parka', 'Down jacket'],
    'Winter coat': ['Winter coat', 'Wool coat', 'Peacoat'],
    'Light jacket': ['Light jacket', 'Bomber jacket', 'Denim jacket'],
    'Sweater': ['Sweater', 'Cardigan', 'Pullover'],
    'Long sleeve shirt': ['Long sleeve shirt', 'Button-down shirt', 'Polo shirt'],
    'Light sweater': ['Light sweater', 'Crew neck', 'V-neck'],
    'T-shirt': ['T-shirt', 'Crew neck', 'V-neck'],
    'Short sleeve shirt': ['Short sleeve shirt', 'Polo shirt', 'Casual shirt'],
    'Light pants': ['Chinos', 'Khakis', 'Lightweight pants'],
    'Thick pants': ['Thick pants', 'Jeans', 'Heavy-duty pants'],
    'Winter pants': ['Winter pants', 'Insulated pants', 'Fleece-lined pants'],
    'Tank top': ['Tank top', 'Sleeveless shirt', 'Muscle tee'],
    'Shorts': ['Shorts', 'Athletic shorts', 'Casual shorts'],
    'Dress': ['Dress', 'Sundress', 'Summer dress'],
    'Rain jacket': ['Rain jacket', 'Waterproof jacket', 'Windbreaker'],
    'Umbrella': ['Compact umbrella', 'Windproof umbrella', 'Large umbrella'],
    'Waterproof shoes': ['Waterproof boots', 'Rain shoes', 'Waterproof sneakers'],
    'Waterproof boots': ['Waterproof boots', 'Snow boots', 'Winter boots'],
    'Snow jacket': ['Snow jacket', 'Insulated jacket', 'Winter coat'],
    'Waterproof gloves': ['Waterproof gloves', 'Winter gloves', 'Insulated gloves'],
    'Windbreaker': ['Windbreaker', 'Wind jacket', 'Lightweight jacket'],
    'Secure hat': ['Beanie', 'Winter hat', 'Baseball cap'],
    'Moisture-wicking fabrics': ['Moisture-wicking shirt', 'Athletic wear', 'Performance fabric'],
    'Extra deodorant': ['Deodorant', 'Antiperspirant', 'Body spray'],
    'Sunglasses': ['Sunglasses', 'Polarized sunglasses', 'UV protection glasses'],
    'Hat': ['Baseball cap', 'Sun hat', 'Bucket hat'],
    'Sunscreen': ['SPF 30+ sunscreen', 'Broad spectrum sunscreen', 'Water-resistant sunscreen'],
    'Light-colored clothing': ['Light colored shirt', 'Light pants', 'Light sweater']
  }
};

export function getGenderSpecificItems(baseItems: string[], gender: Gender): string[] {
  return baseItems.map(item => {
    const genderItems = genderSpecificItems[gender][item];
    return genderItems ? genderItems[Math.floor(Math.random() * genderItems.length)] : item;
  });
}

